Repository alexanderjaye/remedic-app, pull requests merged in 2021-02, with the labels that each got.

#85 Au fe chat style
  client/src/Components/Pages/ConsultationChat/ConsultationChat.tsx
  client/src/Components/Pages/DoctorChat/DoctorChat.tsx
  client/tailwind.config.js
Labels: F-Livechat, FE

#87 MP FE Client GQL Queries
  client/package-lock.json
  client/package.json
  client/src/services/graphqlService/queries.ts
Labels: FE

#92 Fix: fixed incorrect type of painLevel field on the consultation inp…
  server/src/graphql/resolvers/consultation.resolver.ts
Labels: BE

#100 MP front-end gql mutations
  client/src/services/graphqlService/mutations.ts
  client/src/services/graphqlService/queries.ts
Labels: FE

#101 Mp fe react query setup
  client/package-lock.json
  client/package.json
  client/src/index.tsx
  client/src/services/graphqlService/index.ts
Labels: FE

#104 MP FE Spinner component
  client/src/Components/Globals/Spinner/Spinner.tsx
  client/src/Components/Globals/Spinner/loading.svg
  client/tailwind.config.js
Labels: FE

#111 Mp FE Symptoms Filter
  client/src/Components/Pages/PatientSymptoms/PatientSymptoms.tsx
  client/src/Contexts/Consultation.context.tsx
Labels: FE

#175 MP BE & FE implement consultation end
  client/src/Components/Pages/ConsultationChat/ConsultationChat.tsx
  client/src/Components/Pages/DoctorChat/DoctorChat.tsx
  client/src/Contexts/Consultation.context.tsx
  client/src/hooks/useChat.ts
  server/src/chat/index.ts
Labels: BE, FE

#181 Mp fe/ge consultation isactive
  client/src/Components/Pages/ConsultationChat/ConsultationChat.tsx
  client/src/Components/Pages/PatientQueue/PatientCard.tsx
  client/src/Components/Pages/PatientQueue/PatientQueue.tsx
  client/src/Contexts/Doctor.context.tsx
  client/src/services/graphqlService/queries.ts
  client/src/types.tsx
  server/src/graphql/resolvers/consultation.resolver.ts
Labels: BE, FE

#194 Mp FE Consultation Mutation
  client/src/Components/Pages/DoctorChat/DoctorChat.tsx
  client/src/Contexts/Doctor.context.tsx
  client/src/services/graphqlService/mutations.ts
  client/src/services/graphqlService/queries.ts
Labels: FE
